The contents of the new file will be the modified ".github/workflows/main.yml" file. The specific modifications will depend on the identified issues causing the failure in the GitHub Actions workflow. We will make the necessary changes to address these issues.

Commit message: "feat/fix: Fix failing GitHub Actions workflow"
