The contents of the updated ".github/workflows/main.yml" file:

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build and deploy
        run: |
          # Add build and deploy steps here

This updated workflow file includes the following steps:

1. Checkout repository: This step checks out the repository code.
2. Set up Python: This step sets up the Python environment.
3. Install dependencies: This step installs the required dependencies specified in the "requirements.txt" file.
4. Run tests: This step runs the pytest command to execute the tests.
5. Build and deploy: This step should be updated with the necessary build and deploy steps specific to your project.

Please make sure to replace the comment "# Add build and deploy steps here" with the actual build and deploy commands or scripts relevant to your project.
