import yaml
import re

def install_gitpython_step(yaml_contents):
    # Find the position of the first occurrence of the "steps" key
    steps_position = re.search(r'\bsteps\b', yaml_contents).start()

    # Insert a new step before the found position
    yaml_contents.insert(steps_position, {
        'name': 'Install GitPython',
        'run': 'pip install GitPython'
    })

def update_workflow_file(file_path):
    # Read the contents of the existing YAML file
    with open(file_path, 'r') as file:
        yaml_contents = yaml.safe_load(file)

    # Add the new step to install GitPython
    install_gitpython_step(yaml_contents)

    # Write the modified YAML contents back to the file
    with open(file_path, 'w') as file:
        yaml.safe_dump(yaml_contents, file)

# Update the workflow file
update_workflow_file('.github/workflows/main.yml')
