The contents of the updated ".github/workflows/main.yml" file:

name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build and deploy
        run: |
          # Add build and deploy commands here

This updated configuration file includes the following changes:
- Added a step to checkout the repository.
- Added a step to set up Python version 3.8.
- Added a step to install dependencies using the requirements.txt file.
- Added a step to run tests using pytest.
- Added a placeholder step for build and deploy commands. Replace this with the actual commands needed for your project.

Please note that you should replace the placeholder step with the appropriate build and deploy commands for your project.

When writing unit tests, ensure to cover all edge cases and make use of mocks when necessary. Create test data as needed to thoroughly test the functionality of the updated configuration file.

Commit message: "feat/fix: Update GitHub Actions configuration file"
